esphome:
  name: laundry-monitor
  platform: esp32
  board: ttgo-t7-v14-mini32

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "b3e53ad80cb56e05e942aed1572be451"

sensor:
  - platform: homeassistant
    name: "Dryer Temperature"
    entity_id: sensor.dryer_temperature
    id: dryer_temperature
  - platform: homeassistant
    name: "Dryer Humidity"
    entity_id: sensor.dryer_humidity
    id: dryer_humidity
  - platform: homeassistant
    name: "Washing Machine (W)"
    entity_id: sensor.washing_machine_electric_consumed_w
    id: washing_machine_w

select:
  platform: template
  options: 
    - "Idle"
    - "Running"
    - "Finishing"
  optimistic: True
  name: Dryer Status
  id: dryer_status

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laundry-Monitor Fallback Hotspot"
    password: "UX0RUtBf2W75"

captive_portal:

image:
  - file: "tumble-dryer.png"
    id: dryer_idle_icon
    type: transparent_binary
    resize: 50x50
  - file: "washing-machine.png"
    id: washing_machine_icon
    type: transparent_binary
    resize: 50x50

font:
  - file: 'Roboto-Regular.ttf'
    id: roboto
    size: 20

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 17

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b74
    update_interval: 30s
    full_update_every: 36000
    reset_duration: 2ms
    rotation: 90
    lambda: |-
      // %% - literal % sign
      it.printf(45, 1, id(roboto), "Dryer Temp: %.0f°F", id(dryer_temperature).state);
      it.printf(45, 20, id(roboto), "Dryer Humidity: %.0f%%", id(dryer_humidity).state);
      it.printf(45, 50, id(roboto), "Washing Machine: %.0fW", id(washing_machine_w).state);
      it.image(2,2, id(dryer_idle_icon));
      it.image(2, 50, id(washing_machine_icon));
      it.printf(45, 70, id(roboto), "Dryer Status: %", id(dryer_status));
